name: Build and Push React App to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: agent

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
            client-id: 6deb65d7-e78e-4edf-b4f9-923a04f5c439
            tenant-id: 86bd8535-9c67-42f5-b4b5-8f19dbd5d717
            subscription-id: b4235c62-725e-4da6-9d12-296ccb04cb57
           
            
        

      # Step 3: Login to Azure Container Registry (ACR)
      - name: Azure ACR Login
        run: az acr login --name rohanacr1.azurecr.io  # e.g. myregistry123

      # Step 4: Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t rohanacr1.azurecr.io/reactapp:${{ github.run_number }} .

      # Step 5: Push image to ACR
      - name: Push Docker image
        run: |
          docker push rohanacr1.azurecr.io/reactapp:${{ github.run_number }}
