name: Build and Push React App to ACR

on:
  workflow_dispatch:  #

jobs:
  build:
    runs-on: agent

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure using Federated Identity (OIDC)
      - name: Azure Login 
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           
            
        

      # Step 3: Login to Azure Container Registry (ACR)
      - name: Azure ACR Login
        run: az acr login --name rohanacr1.azurecr.io  # e.g. myregistry123

      # Step 4: Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t rohanacr1.azurecr.io/reactapp:${{ github.run_number }} .

      # Step 5: Push image to ACR
      - name: Push Docker image
        run: |
          docker push rohanacr1.azurecr.io/reactapp:${{ github.run_number }}
